### ISSUE TITLE
[dapp] Call of DApp function is never completed

### ISSUE THREAD

**Issue by seland** [Bit-Nation/panthalassa#69]
I worked on a DApp using:
 - pangea-sdk v0.9.1
 - pangea-cli v0.3.7
 - Pangea commit [590a5aea0faf4802a8acb1f6f9a14e4491476775](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/tree/590a5aea0faf4802a8acb1f6f9a14e4491476775)
 - Panthalassa commit [3266acffbd1ddd69ad2552d3f7a33cde6ed061ea](https://github.com/Bit-Nation/panthalassa/tree/3266acffbd1ddd69ad2552d3f7a33cde6ed061ea) (included into Pangea).

DApp code is [that](https://github.com/Bit-Nation/dapp-send-request-money/tree/993a62f264cfef0e307ec7db527311c3af5a1c25).

The issue is that CallDAppFunction is never finished, therefore promise returned by it is always pending.

Steps to reproduce:
 - I connect DApp host and load the DApp, wait until it's send to Pangea.
 - Close Pangea app.
 - Open Pangea app, wait until DApp is started.
 - Go to chat tab, tap on plus and select Send/request money DApp.
 - Add breakpoints before and after `CallDAppFunction` in `Panthalassa.m`.
 - Tap on `TAP ME` button.
 - Row before `CallDAppFunction` is executed, row after is not.

**Comment by florianlenz** [comment]
Thanks for the report. Fix discuss in private, I always pass in a callback to the function calls that HAS to be called (sorry that I forgot to tell you). Closing this, feel free to re open it
