### ISSUE TITLE
[chat] chat: key required

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/panthalassa#76]
## Problem
When we try to send a message via the `SendMessage` method in the panthalassa package `root` package. It must be related to the `chat` package since the logger says `chat: key required`. it could also be that it's logging an error returned by another package in the chat package. The way to debug it is, to use `NewChat` of the chat package to setup a new instance. 

A short notion on the chat workflow: 
1. when calling `SavePrivateMessage` it's persisted in the database and we return as soon as it's persisted. 
2. After it got persisted, the handler (in the chat package) will be triggered and it will put the message into the queue
3. After the message reference got persisted into the queue it will try to send the message

## acceptance criteria

**Comment by borjantrajanoski** [comment]
Fixed, travis is passing here.
https://github.com/Bit-Nation/panthalassa/commit/228d2efbd4028baed6468b493428b5259e632db2
