### ISSUE TITLE
[engine] smart contracts

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/panthalassa#80]
## Feature / Issue
Currently we are missing the functionality to interact with smart contracts. Since ether.js took years (ok, minutes - but still way too much) to load in the otto vm we couldn't deliver smart contracts. However, we need smart contracts in the VM asap. There are two options: 

1. We build a wrapper around geth smart contracts
2. We switch the vm (#81) and get ether.js running.

Switching the VM is probably a better idea since otto vm doesn't provide a few features that we need (e.g. sandboxing)

## Acceptance criteria
- [ ] interact with smart contract (read, write)

## Depends on:
- #81

**Comment by borjantrajanoski** [comment]
@kevowevo this will be done at the 28th
