### ISSUE TITLE
[documents] document storage

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/panthalassa#88]
## Feature / Issue
We need a document storage, documents can be pictures or pdfs or something else that is like a document. The content of the document should always be encrypted. 

As of now, fields of the database struct should be: 
- `title` (string)
- `content` (aes.CipherText)
- `created_at` (time.Time)
- `type` (string) might be the mime type

There are a few unknowns, e.g. I am not sure if we will receive the mime type from the client. As well as the format (might be base64) that need to be clarified with the mobile team. 

## Acceptance Criteria
- [ ] tests
- [ ] call module for create, read, updated and delete.
- [ ] logic for persisting

## Dependencies
- [storm](https://github.com/Bit-Nation/panthalassa/issues/82 )

**Comment by borjantrajanoski** [comment]
@kevowevo this will be done at the 28th
